# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main", "dev" ]

jobs:

  build:
    runs-on: ["gha-runner-scale-set"]
    steps:
    - uses: actions/checkout@v3
    - run: sudo apt-get update && sudo apt-get install -y apt-get install build-essential
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: 1.19

    - name: Download
      run: go mod download

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
